{% set name = "spot2cell" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spot2cell-{{ version }}.tar.gz
  sha256: 7a0b89ffa898c8fd462c62a629969c1383b318c9658b6db8bc02b9469c3c0da9

build:
  entry_points:
    - spots2cells = spot2cell.scripts.spots2cells:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - numpy
    - tifffile

test:
  imports:
    - spot2cell
  commands:
    - pip check
    - spots2cells --help
  requires:
    - pip

about:
  home: https://github.com/SchapiroLabor/spot2cell
  summary: From a X,Y list of detected spots, assigns each spot to a cell based on a segmentation mask
  license: AGPL-3.0-only
  license_file: LICENSE
  doc_url: https://github.com/SchapiroLabor/spot2cell
  dev_url: https://github.com/SchapiroLabor/spot2cell

extra:
  recipe-maintainers:
    - migueLib
